cluster:
  domain: outbound.vz.bos2.lab
  name: hub

host:
  interface: ens1f0
  stack: ipv4
  hostname: hub.outbound.vz.bos2.lab
  ip: 192.168.58.80
  dns: 192.168.58.15
  gateway: 192.168.58.1
  mac: de:ad:be:ff:10:01
  prefix: 25
  machine_network_cidr: 192.168.58.0/25
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/vda

day0:
  workload_partition: true
  kdump: true
  ptp: false
  sriov: false
  storage: true
  accelerate: true
  gitops: true
  rhacm: true
  talm: true

cpu:
  isolated: 16-47
  reserved: 0-15

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub
