---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mce.outbound.vz.bos2.lab
  storageClassDevices:
    - storageClassName: local-storage
      volumeMode: Filesystem
      devicePaths:
        - /dev/vdb
        - /dev/vdc