apiVersion: v1
data:
  config.yaml: |
    alertmanagerMain:
      enabled: false
    telemeterClient:
      enabled: false
    prometheusK8s:
      retention: 24h
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring