cluster:
  domain: outbound.vz.bos2.lab
  name: sno148

host:
  interface: ens1f0
  hostname: sno148.outbound.vz.bos2.lab
  mac: b4:96:91:b4:9d:f0
  ipv6:
    enabled: true
    dhcp: false
    ip: 2600:52:7:58::48
    dns:
      - 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
  disk: /dev/nvme0n1

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: true
  http: http://[2600:52:7:58::15]:3128
  https: http://[2600:52:7:58::15]:3128
  noproxy: 2600:52:7:58::/64,localhost,127.0.0.1

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy

iso:
  address: http://192.168.58.15/iso/sno148.iso