cluster:
  domain: outbound.vz.bos2.lab
  name: sno148

host:
  interface: ens1f0
  stack: ipv4
  hostname: sno148.outbound.vz.bos2.lab
  ip: 192.168.58.48
  dns: 192.168.58.15
  gateway: 192.168.58.1
  mac: b4:96:91:b4:9d:f0
  prefix: 25
  cluster_network_cidr: 10.128.0.0/14
  cluster_network_host_prefix: 23
  machine_network_cidr: 192.168.58.0/25
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/nvme0n1

day1:
  workload_partition: true
  kdump: true
  ptp: true
  sriov: true
  storage: true
  accelerate: true
  gitops: true
  rhacm: false
  talm: false
  amq: false

day2:
  performance_profile:
    name: sno-perfprofile
    enabled: true
  tuned: true
  kdump_tuned: false
  ptp_amq: true
  cluster_monitor: true
  operator_hub: true
  console: true
  network_diagnostics: true

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy

iso:
  address: http://192.168.58.15/iso/sno148.iso