cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org

  #optional: https://docs.openshift.com/container-platform/4.14/post_installation_configuration/enabling-cluster-capabilities.html
  #if not present:
  #for 4.12 it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  # for 4.13+, it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  #      - NodeTuning
  capabilities:
    #None|vCurrent|v4.12|v4.14 ...
    baselineCapabilitySet: None
    additionalEnabledCapabilities:
      - marketplace
host:
  hostname: sno148.outbound.vz.bos2.lab
  interface: ens1f0
  mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns:
      - 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
    #optional, default 10.128.0.0/14
    #cluster_network_cidr: 10.128.0.0/14
    #optional, default 23
    #cluster_network_host_prefix: 23
  ipv6:
    enabled: false
    dhcp: false
    ip: 2600:52:7:58::48
    dns:
      - 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
    #optional, default fd01::/48
    #cluster_network_cidr: fd01::/48
    #optional, default 64
    #cluster_network_host_prefix: 64
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/nvme0n1

day1:
  workload_partition: true
  kdump: 
    enabled: true
    #set blacklist_ice as true on HPE servers
    blacklist_ice: false
    #secure boot, will have additional kernel argument efi=runtime
    secure_boot: false
  boot_accelerate: true
  #4.13+ only, whether enable crun as default container runtime
  crun: true
  #4.14, https://issues.redhat.com/browse/OCPBUGS-17660
  rcu_normal: true
  #4.14, reduce a node boot and fix a race condition issue in sriov operator
  sriov_kernel: true
  #4.14, sync the node time from ntp when node reboot and ptp got involved
  sync_time_once: true
  #whether enable cgroup v1; 4.14-4.15: will enable cgv1 by default, 4.16+ will enable cgv2 by default
  cgv1: true
  #whether disable the marketplace operator, default: false
  disable_marketplace: true
  container_storage:
    enabled: false
    device: /dev/nvme0n1
    startMiB: 250000
    sizeMiB: 0
  #ztp_hub=true will enable rhacm/lvm/gitops/talm on the cluster
  ztp_hub: false
  operators:
    ptp:
      enabled: true
      #if you want to stay on a particular version ptp-operator.4.12.0-202402081808
      #version: ptp-operator.4.12.0-202402081808
    sriov:
      enabled: true
      #if you want to stay on a particular version sriov-network-operator.v4.12.0-202402081808
      #version: sriov-network-operator.v4.12.0-202402081808
    local-storage:
      enabled: true
      #if you want to stay on a particular version local-storage-operator.v4.12.0-202403082008
      #version: local-storage-operator.v4.12.0-202403082008
    gitops:
      enabled: false
    rhacm:
      enabled: false
    talm:
      enabled: false
    mce:
      enabled: false
    lvm:
      enabled: false
    fec:
      enabled: false
      #if you want to stay on a particular version sriov-fec.v2.7.2
      #version: sriov-fec.v2.7.2
    cluster-logging:
      enabled: false
      #if you want to stay on a particular version
      #version: cluster-logging.v5.8.3
    adp:
      enabled: false
      #set the channel
      #channel: stable-1.3
      #set the version
      #version: 1.3.1
    lca:
      enabled: false
      #set the channel
      #channel: stable
      #set the version
      #version: v4.16.0-89

day2:
  performance_profile:
    enabled: true
    #in case you want to specify the performance profile name
    name: sno-perfprofile
    #optional, present if want to set user_level_networking as true
    net:
      user_level_networking: true
    #optional for hardware tuning, OCP 4.16
    hardwareTuning:
      isolatedCpuFreq: 2500000
      reservedCpuFreq: 2800000
  tuned_profile: 
    enabled: true
    #for wrong bios settings, if passive mode is used, set intel_pstate=active
    cmdline_pstate: intel_pstate=active
    #in case you want to generate kdump for some special scenarios (used in lab)
    kdump: false
    sysfs:
      #cap the intel_pstate peak frequency at 2.5Ghz, used in 4.14. 4.16 can set day2.performance_profile.hardwareTuning
      cpufreq_max_freq: 2500000
  ptp:
    #ptpconfig type: choose any of them: disabled|ordinary|boundary
    #chronyd service will be disabled if ordinary or boundary being selected
    ptpconfig: disabled
    ordinary_clock:
      #name: crdu-ptp-ordinary-clock
      interface: ens1f0
    boundary_clock:
      # only supported for 4.16+, when not enabled, the profiles[0] is used for system clock, 4.15 or earlier versions must set it as false
      ha_enabled: false
      #name (default): crdu-boundary-clock-ptp-config
      #name: crdu-boundary-clock-ptp-config
      profiles:
      - name: bc-profile-nic1
        slave: ens1f0
        masters:
          - ens1f1
          - ens1f2
          - ens1f3

      - name: bc-profile-nic2
        slave: ens2f0
        masters:
          - ens2f1
          - ens2f2
          - ens2f3

    #enable the ptp event, if true, will set summary_interval as -4, otherwise it will stay at 0
    enable_ptp_event: true
    #enable log_reduce, when setting as true it will reduce(filter all) the ptp logs
    log_reduce: true

  #enable the cluster monitoring tuning
  cluster_monitor_tuning: true
  #disable the network diagnostics
  disable_network_diagnostics: true
  #4.14 disable the olm pprof(collect-profile cronjob)
  disable_olm_pprof: true
  disable_operator_auto_upgrade: true

  #https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
  sriov:
    enable_injector: false
    enable_webhook: false

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub
extra_manifests: /root/sno-vdu/sno148-extra-manifests

#set it in a disconnected env
additional_trust_bundle: /root/registry/ca-bundle.crt
#set it in a disconnected env, mirror/mirror-operators.sh can be used to generate the file
container_registry:
  image_source: /root/registry/local-mirror.yaml
  prega: false
  disable_catalogsources:
    - redhat-marketplace
    - community-operators
    #- certified-operators
    #- redhat-operators

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy
  kvm_uuid:
  
iso:
  address: http://192.168.58.15/iso/sno148.iso