cluster:
  domain: outbound.vz.bos2.lab
  name: sno148

host:
  interface: ens1f0
  stack: ipv4
  hostname: sno148.outbound.vz.bos2.lab
  ip: 192.168.58.48
  dns: 192.168.58.15
  gateway: 192.168.58.1
  mac: b4:96:91:b4:9d:f0
  prefix: 25
  cluster_network_cidr: 10.128.0.0/14
  cluster_network_host_prefix: 23
  machine_network_cidr: 192.168.58.0/25
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/nvme0n1

day1:
  workload_partition: true
  kdump: 
    enabled: true
    #set blacklist_ice as true on HPE servers
    blacklist_ice: false
  boot_accelerate: true
  operators:
    ptp: true
    sriov: true
    storage: true
    gitops: true
    rhacm: false
    talm: false
    amq: false

day2:
  performance_profile:
    enabled: true
    #in case you want to specify the performance profile name
    name: sno-perfprofile
  tuned_profile: 
    enabled: true
    #for wrong bios settings, if passive mode is used, set intel_pstate=active
    cmdline_pstate: intel_pstate=active
    #in case you want to generate kdump for some special scenarios (used in lab)
    kdump: true
  #enable the amq interconnector for ptp  
  enable_ptp_amq_router: true
  #enable the cluster monitoring tuning
  cluster_monitor_tuning: true
  #enable the opertor hub tuning: disable unused catalogsources
  operator_hub_tuning: true
  #disable the ocp console operator
  disable_ocp_console: true
  #disable the network diagnostics
  disable_network_diagnostics: true
  disable_operator_auto_upgrade: true

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy
  node_uuid: 
  
iso:
  address: http://192.168.58.15/iso/sno148.iso