cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org

  #optional: https://docs.openshift.com/container-platform/4.14/post_installation_configuration/enabling-cluster-capabilities.html
  #if not present:
  #for 4.12 it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  # for 4.13+, it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  #      - NodeTuning
  capabilities:
    #None|vCurrent|v4.12|v4.14 ...
    baselineCapabilitySet: None
    additionalEnabledCapabilities:
      - marketplace
host:
  hostname: sno148.outbound.vz.bos2.lab
  interface: ens1f0
  mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns: 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
    #optional, default 10.128.0.0/14
    #cluster_network_cidr: 10.128.0.0/14
    #optional, default 23
    #cluster_network_host_prefix: 23
  ipv6:
    enabled: false
    dhcp: false
    ip: 2600:52:7:58::48
    dns: 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
    #optional, default fd01::/48
    #cluster_network_cidr: fd01::/48
    #optional, default 64
    #cluster_network_host_prefix: 64
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/nvme0n1

day1:
  workload_partition: true
  kdump: 
    enabled: true
    #set blacklist_ice as true on HPE servers
    blacklist_ice: false
    #secure boot, will have additional kernel argument efi=runtime
    secure_boot: false
  boot_accelerate: true
  #4.13+ only, whether enable crun as default container runtime
  crun: true
  rcu_normal: true
  sriov_kernel: true
  sync_time_once: true
  #ztp_hub=true will enable rhacm/lvm/gitops/talm on the cluster
  ztp_hub: false
  operators:
    ptp: true
    sriov: true
    storage: true
    gitops: false
    rhacm: false
    talm: false
    mce: false
    lvm: false
    fec: false
    cluster_logging: false

day2:
  performance_profile:
    enabled: true
    #in case you want to specify the performance profile name
    name: sno-perfprofile
  tuned_profile: 
    enabled: true
    #for wrong bios settings, if passive mode is used, set intel_pstate=active
    cmdline_pstate: intel_pstate=active
    #in case you want to generate kdump for some special scenarios (used in lab)
    kdump: false

  ptp:
    #ptpconfig type: choose any of them: disabled|ordinary|boundary
    #chronyd service will be disabled if ordinary or boundary being selected
    ptpconfig: disabled
    ordinary_clock:
      #name: crdu-ptp-ordinary-clock
      interface: ens1f0
    boundary_clock:
      #name: crdu-boundary-clock-ptp-config
      slave: ens1f0
      masters:
        - ens1f1
        - ens1f2
        - ens1f3
    #enable the ptp event
    enable_ptp_event: false
    
  #enable the cluster monitoring tuning
  cluster_monitor_tuning: true
  #enable the operator hub tuning: disable unused catalog sources
  operator_hub_tuning: true
  #disable the network diagnostics
  disable_network_diagnostics: true
  #disable the olm pprof(collect-profile cronjob)
  disable_olm_pprof: true
  disable_operator_auto_upgrade: true

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub
extra_manifests: /root/sno-vdu/sno148-extra-manifests

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy
  kvm_uuid:
  
iso:
  address: http://192.168.58.15/iso/sno148.iso