cluster:
  domain: outbound.vz.bos2.lab
  name: sno130

host:
  interface: ens1f0
  stack: ipv4
  hostname: sno130.outbound.vz.bos2.lab
  ip: 192.168.14.29
  dns: 192.168.58.15
  gateway: 192.168.14.1
  mac: b4:96:91:da:5a:ec
  prefix: 27
  machine_network_cidr: 192.168.14.0/27
  vlan:
    enabled: false
    name: ens1f0.58
    id: 58
  disk: /dev/nvme0n1

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub
