cluster:
  domain: outbound.vz.bos2.lab
  name: testkvm

host:
  interface: ens1f0
  hostname: testkvm.outbound.vz.bos2.lab
  mac: de:ad:be:ff:10:85
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.70
    dns: 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
  disk: /dev/vda

day1:
  workload_partition: false
  kdump: 
    enabled: false
    #set blacklist_ice as true on HPE servers
    blacklist_ice: false
  boot_accelerate: true
  #4.13+ only, whether enable crun as default container runtime
  crun: false
  operators:
    ptp: false
    sriov: false
    storage: false
    gitops: false
    rhacm: true
    talm: false
    amq: false
    lvm: true

day2:
  performance_profile:
    enabled: false
    #in case you want to specify the performance profile name
    name: sno-perfprofile
  tuned_profile: 
    enabled: false
    #for wrong bios settings, if passive mode is used, set intel_pstate=active
    cmdline_pstate: intel_pstate=active
    #in case you want to generate kdump for some special scenarios (used in lab)
    kdump: false

  ptp:
    #ptpconfig type: choose any of them: disabled|ordinary|boundary
    #chronyd service will be disable if ordinary or boundary being selected
    ptpconfig: disabled
    ordinary_clock:
      #name: crdu-ptp-ordinary-clock
      interface: ens1f0
    boundary_clock:
      #name: crdu-boundary-clock-ptp-config
      slave: ens1f0
      masters:
        - ens1f1
        - ens1f2
        - ens1f3
    #enable the amq inter-connector
    enable_ptp_amq_router: false
    

cpu:
  isolated: 16-47
  reserved: 0-15

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: ./pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

bmc:
  address: 192.168.58.15:8080
  username: Administrator
  password: dummy
  node_uuid: 11111111-1111-1111-1234-000000000000

iso:
  address: http://192.168.58.15/iso/testkvm.iso
