apiVersion: v1
baseDomain: outbound.vz.bos2.lab
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: sno148
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.58.0/25
platform:
  none: {}
pullSecret: ''
sshKey: 'ssh-rsa bzhai@fedora'