apiVersion: v1
baseDomain: outbound.vz.bos2.lab
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: sno148
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
    - fd02::/112
  machineNetwork:
  - cidr: 2600:52:7:58::/64
platform:
  none: {}
pullSecret: ''
sshKey: 'ssh-rsa bzhai@fedora'