---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno130
rendezvousIP: 192.168.14.29
hosts:
  - hostname: sno130.outbound.vz.bos2.lab
    interfaces:
      - name: ens1f0
        macAddress: b4:96:91:da:5a:ec
    rootDeviceHints:
      deviceName: /dev/nvme0n1
    networkConfig:
      interfaces:
        - name: ens1f0
          type: ethernet
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 192.168.14.29
                prefix-length: 27
            dhcp: false
          
            ipv6:
              enabled: false
          
      dns-resolver:
        config:
          server:
            - 192.168.58.15
            
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.14.1
            next-hop-interface: ens1f0
            table-id: 254
          