apiVersion: v1
baseDomain: outbound.vz.bos2.lab
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: sno130
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
    - marketplace
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.14.0/27
platform:
  none: {}
pullSecret: ''
sshKey: ''